name: Build and Release Graphical Bootloader

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Tag Name
        id: extract_tag_name
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        run: |
          gh release create ${{ steps.extract_tag_name.outputs.tag_name }} --title "Release ${{ steps.extract_tag_name.outputs.tag_name }}" --notes "Release notes for ${{ steps.extract_tag_name.outputs.tag_name }}" --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        board:
          - { name: "esp32-s3-box-3", sdkconfig: "sdkconfig.defaults.esp-box-3" }
          - { name: "esp32-s3-box", sdkconfig: "sdkconfig.defaults.esp-box" }
          #- { name: "esp32-p4", sdkconfig: "sdkconfig.defaults.esp32_p4_function_ev_board" }
          - { name: "m5stack-cores3", sdkconfig: "sdkconfig.defaults.m5stack_core_s3" }
    runs-on: ubuntu-22.04
    container: espressif/idf:release-v5.3

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set SDKCONFIG_DEFAULTS
        run: echo "SDKCONFIG_DEFAULTS=${{ matrix.board.sdkconfig }}" >> $GITHUB_ENV

      - name: Build the main application and sub-applications
        run: |
          . /opt/esp/idf/export.sh
          cmake -Daction=select_board -P Bootloader.cmake
          cmake -Daction=build_all_apps -P Bootloader.cmake

      - name: Merge binaries into a single image
        run: |
         . /opt/esp/idf/export.sh
         cmake -Daction=merge_binaries -P Bootloader.cmake
         mv build/combined.bin build/graphical-bootloader-${{ matrix.board.name }}.bin


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphical-bootloader-${{ matrix.board.name }}.bin
          path: build/graphical-bootloader-${{ matrix.board.name }}.bin

      - name: Merge binaries into a uf2 image
        run: |
         . /opt/esp/idf/export.sh
         cmake -Daction=merge_binaries_uf2 -P Bootloader.cmake
         mv build/uf2.bin build/graphical-bootloader-${{ matrix.board.name }}.uf2

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphical-bootloader-${{ matrix.board.name }}.uf2
          path: build/graphical-bootloader-${{ matrix.board.name }}.uf2

  upload-release-assets:
    needs: build-and-upload
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Extract Tag Name
        id: extract_tag_name
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Rename and Upload Release Assets
        run: |
          ls -l ./artifacts
          for file in ./artifacts/*.bin ./artifacts/*.uf2; do
            gh release upload ${{ steps.extract_tag_name.outputs.tag_name }} "${file}" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
